# Stage 1: Build stage
FROM node:latest AS build

# Set working directory
WORKDIR /app/lnt-frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Production stage
FROM nginx:alpine

# Copy built files from the previous stage
COPY --from=build /app/lnt-frontend/dist /usr/share/nginx/html

# Copy GLTF file to the appropriate directory in Nginx HTML folder
COPY ./src/components/models/Ram-Mandir.gltf /usr/share/nginx/html/src/components/models/
COPY ./src/components/models/scene.bin /usr/share/nginx/html/src/components/models/

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
